apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai1-deployment
  namespace: cjarcau
  labels:
    app: ai1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai1
  template:
    metadata:
      labels:
        app: ai1
    spec:
      containers:
      - name: ai1
        image: scr4pp/ai1:arm5
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: api
          containerPort: 3000
        imagePullPolicy: IfNotPresent
